name: Publish To GPR
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  publish-to-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js And Setup .npmrc
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope       : '@neos21'
          always-auth : true
        env :
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Can Publish
        run : npx can-npm-publish --verbose
        env :
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run : npm install
        env :
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run : npm run build --if-present
        env :
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run : npm publish --access=public
        env :
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
